server:
  port: 8084

spring:
  application:
    name: gateway-service
  boot:
    admin:
      client:
        url: http://localhost:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
