server:
  port: 8085

spring:
  application:
    name: doctor-appointment-service
  boot:
    admin:
      client:
        url: http://localhost:8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
